export const inputSelector = '[data-testid="input"]';
export const buttonSelector = '[data-testid="button"]';
export const circleSelector = '[class*=circle_content__]';
export const circleBorderSelector = '[class^=circle_circle__]';
export const circleIndexSelector = '[class*="circle_index__"]';
export const addButtonSelector = '[data-testid="addButton"]';
export const removeButtonSelector = '[data-testid="removeButton"]';
export const clearButtonSelector = '[data-testid="clearButton"]';
export const circleHeadSelector = '[class*=circle_head__]';
export const circleTailSelector = '[class*=circle_tail]';
export const smallCircleSelector = '[class*=circle_small__]';
export const valueInputSelector = '[data-testid="valueInput"]';
export const indexInputSelector = '[data-testid="indexInput"]';
export const addHeadButton = '[data-testid="addHeadButton"]';
export const addTailButton = '[data-testid="addTailButton"]';
export const removeHeadButton = '[data-testid="removeHeadButton"]';
export const removeTailButton = '[data-testid="removeTailButton"]';
export const addByIndexButton = '[data-testid="addByIndexButton"]';
export const removeByIndexButton = '[data-testid="removeByIndexButton"]';
export const defaultBorderColor = '4px solid rgb(0, 50, 255)';
export const changingBorderColor = '4px solid rgb(210, 82, 225)';
export const modifiedBorderColor = '4px solid rgb(127, 224, 81)';
